# https://taskfile.dev

version: '3'

tasks:
  install:
    cmds:
      - poetry install
  run:
    cmds:
      - poetry run uvicorn src.app:app --host 0.0.0.0 --port 8000
  
  format: poetry run isort . && poetry run black .
